[package]
name = "r2d2_gluster"
version = "0.1.1"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
description = "r2d2 managed gluster connections"
license = "MIT"

[dependencies]
gfapi-sys  = "~0.3" # gfapi
log = "~0.4"
r2d2 = "~0.8"
